/**
 * WatermelonDB Schema for Astik
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Run 'npm run db:sync' to regenerate
 */

import { appSchema, tableSchema } from "@nozbe/watermelondb";

export const schema = appSchema({
  version: 6,
  tables: [
    tableSchema({
      name: "accounts",
      columns: [
        { name: "balance", type: "number" },
        { name: "created_at", type: "number" },
        { name: "currency", type: "string" },
        { name: "deleted", type: "boolean" },
        { name: "name", type: "string" },
        { name: "type", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "asset_metals",
      columns: [
        { name: "asset_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "item_form", type: "string", isOptional: true },
        { name: "metal_type", type: "string" },
        { name: "purity_fraction", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "weight_grams", type: "number" },
      ],
    }),

    tableSchema({
      name: "assets",
      columns: [
        { name: "created_at", type: "number" },
        { name: "currency", type: "string" },
        { name: "deleted", type: "boolean" },
        { name: "is_liquid", type: "boolean" },
        { name: "name", type: "string" },
        { name: "notes", type: "string", isOptional: true },
        { name: "purchase_date", type: "number" },
        { name: "purchase_price", type: "number" },
        { name: "type", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "bank_details",
      columns: [
        { name: "account_id", type: "string", isIndexed: true },
        { name: "account_number", type: "string", isOptional: true },
        { name: "bank_name", type: "string", isOptional: true },
        { name: "card_last_4", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "sms_sender_name", type: "string", isOptional: true },
        { name: "updated_at", type: "number" },
      ],
    }),

    tableSchema({
      name: "budgets",
      columns: [
        { name: "alert_threshold", type: "number" },
        { name: "amount", type: "number" },
        {
          name: "category_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "created_at", type: "number" },
        { name: "currency", type: "string" },
        { name: "deleted", type: "boolean" },
        { name: "name", type: "string" },
        { name: "period", type: "string" },
        { name: "period_end", type: "number", isOptional: true },
        { name: "period_start", type: "number", isOptional: true },
        { name: "status", type: "string" },
        { name: "type", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "categories",
      columns: [
        { name: "color", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "display_name", type: "string" },
        { name: "icon", type: "string" },
        { name: "icon_library", type: "string" },
        { name: "is_hidden", type: "boolean" },
        { name: "is_internal", type: "boolean" },
        { name: "is_system", type: "boolean" },
        { name: "level", type: "number" },
        { name: "nature", type: "string", isOptional: true },
        {
          name: "parent_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "sort_order", type: "number", isOptional: true },
        { name: "system_name", type: "string" },
        { name: "type", type: "string", isOptional: true },
        { name: "updated_at", type: "number" },
        { name: "usage_count", type: "number" },
        { name: "user_id", type: "string", isOptional: true, isIndexed: true },
      ],
    }),

    tableSchema({
      name: "debts",
      columns: [
        { name: "account_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "date", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "due_date", type: "number", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "original_amount", type: "number" },
        { name: "outstanding_amount", type: "number" },
        { name: "party_name", type: "string" },
        { name: "status", type: "string" },
        { name: "type", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "market_rates",
      columns: [
        { name: "aed_egp", type: "number" },
        { name: "aud_egp", type: "number" },
        { name: "bhd_egp", type: "number" },
        { name: "btc_egp", type: "number" },
        { name: "cad_egp", type: "number" },
        { name: "chf_egp", type: "number" },
        { name: "cnh_egp", type: "number" },
        { name: "cny_egp", type: "number" },
        { name: "created_at", type: "number" },
        { name: "dkk_egp", type: "number" },
        { name: "dzd_egp", type: "number" },
        { name: "eur_egp", type: "number" },
        { name: "gbp_egp", type: "number" },
        { name: "gold_egp_per_gram", type: "number" },
        { name: "hkd_egp", type: "number" },
        { name: "inr_egp", type: "number" },
        { name: "iqd_egp", type: "number" },
        { name: "isk_egp", type: "number" },
        { name: "jod_egp", type: "number" },
        { name: "jpy_egp", type: "number" },
        { name: "kpw_egp", type: "number" },
        { name: "krw_egp", type: "number" },
        { name: "kwd_egp", type: "number" },
        { name: "lyd_egp", type: "number" },
        { name: "mad_egp", type: "number" },
        { name: "myr_egp", type: "number" },
        { name: "nok_egp", type: "number" },
        { name: "nzd_egp", type: "number" },
        { name: "omr_egp", type: "number" },
        { name: "palladium_egp_per_gram", type: "number" },
        { name: "platinum_egp_per_gram", type: "number" },
        { name: "qar_egp", type: "number" },
        { name: "rub_egp", type: "number" },
        { name: "sar_egp", type: "number" },
        { name: "sek_egp", type: "number" },
        { name: "sgd_egp", type: "number" },
        { name: "silver_egp_per_gram", type: "number" },
        { name: "timestamp_currency", type: "string", isOptional: true },
        { name: "timestamp_metal", type: "string", isOptional: true },
        { name: "tnd_egp", type: "number" },
        { name: "try_egp", type: "number" },
        { name: "updated_at", type: "number" },
        { name: "usd_egp", type: "number" },
        { name: "zar_egp", type: "number" },
      ],
    }),

    tableSchema({
      name: "profiles",
      columns: [
        { name: "avatar_url", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "display_name", type: "string", isOptional: true },
        { name: "first_name", type: "string", isOptional: true },
        { name: "last_name", type: "string", isOptional: true },
        { name: "notification_settings", type: "string", isOptional: true },
        { name: "onboarding_completed", type: "boolean" },
        { name: "preferred_currency", type: "string" },
        { name: "sms_detection_enabled", type: "boolean" },
        { name: "theme", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "recurring_payments",
      columns: [
        { name: "account_id", type: "string", isIndexed: true },
        { name: "action", type: "string" },
        { name: "amount", type: "number" },
        { name: "category_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "end_date", type: "number", isOptional: true },
        { name: "frequency", type: "string" },
        { name: "frequency_value", type: "number", isOptional: true },
        {
          name: "linked_debt_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "name", type: "string" },
        { name: "next_due_date", type: "number" },
        { name: "notes", type: "string", isOptional: true },
        { name: "start_date", type: "number" },
        { name: "status", type: "string" },
        { name: "type", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "transactions",
      columns: [
        { name: "account_id", type: "string", isIndexed: true },
        { name: "amount", type: "number" },
        { name: "category_id", type: "string", isIndexed: true },
        { name: "counterparty", type: "string", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "currency", type: "string" },
        { name: "date", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "is_draft", type: "boolean" },
        {
          name: "linked_asset_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        {
          name: "linked_debt_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        {
          name: "linked_recurring_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "note", type: "string", isOptional: true },
        { name: "source", type: "string" },
        { name: "type", type: "string" },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "transfers",
      columns: [
        { name: "amount", type: "number" },
        { name: "converted_amount", type: "number", isOptional: true },
        { name: "created_at", type: "number" },
        { name: "currency", type: "string" },
        { name: "date", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "exchange_rate", type: "number", isOptional: true },
        { name: "from_account_id", type: "string", isIndexed: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "to_account_id", type: "string", isIndexed: true },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),

    tableSchema({
      name: "user_category_settings",
      columns: [
        { name: "category_id", type: "string", isIndexed: true },
        { name: "created_at", type: "number" },
        { name: "deleted", type: "boolean" },
        { name: "is_hidden", type: "boolean" },
        { name: "nature", type: "string", isOptional: true },
        { name: "updated_at", type: "number" },
        { name: "user_id", type: "string", isIndexed: true },
      ],
    }),
  ],
});
